Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"  # Ubuntu 18.04

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip libpq-dev python3-dev  # Устанавливаем зависимости для psycopg2
    pip3 install psycopg2 django  # Теперь используем psycopg2, а не binary-версию
  SHELL

  config.vm.provision "file", source: "../empty_file.txt", destination: "/home/vagrant/empty_file.txt"
end